plugins {
    id 'com.android.application'
}

android {
    namespace 'com.okan.xraythermal'
    compileSdk 35

    defaultConfig {
        applicationId 'com.okan.xraythermal'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '2.0-ai'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:face-detection:16.1.7'
    implementation 'com.google.mlkit:object-detection:17.0.2'
}
